# Generated by Django 3.2.5 on 2021-07-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=250)),
                ('meaning', models.TextField()),
                ('example_1', models.TextField(blank=True)),
                ('example_2', models.TextField(blank=True)),
                ('example_3', models.TextField(blank=True)),
                ('example_4', models.TextField(blank=True)),
                ('example_5', models.TextField(blank=True)),
                ('example_6', models.TextField(blank=True)),
                ('example_7', models.TextField(blank=True)),
                ('example_8', models.TextField(blank=True)),
                ('example_9', models.TextField(blank=True)),
                ('example_10', models.TextField(blank=True)),
            ],
        ),
    ]
