# Generated by Django 3.2.5 on 2021-07-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='words',
            options={'verbose_name_plural': 'words'},
        ),
        migrations.AddField(
            model_name='words',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
